var dir_892c880cf19884495b53e8cd9cea50ae =
[
    [ "tests", "dir_ff80aff8238614d55515b0277c24d215.html", "dir_ff80aff8238614d55515b0277c24d215" ],
    [ "addr.cpp", "addr_8cpp.html", "addr_8cpp" ],
    [ "async.cpp", "libs_2karm-sys_2async_8cpp.html", "libs_2karm-sys_2async_8cpp" ],
    [ "bundle.cpp", "bundle_8cpp.html", "bundle_8cpp" ],
    [ "chan.cpp", "chan_8cpp.html", "chan_8cpp" ],
    [ "context.cpp", "karm-sys_2context_8cpp.html", "karm-sys_2context_8cpp" ],
    [ "defs.h", "defs_8h.html", "defs_8h" ],
    [ "dir.cpp", "dir_8cpp.html", "dir_8cpp" ],
    [ "endpoint.cpp", "endpoint_8cpp.html", "endpoint_8cpp" ],
    [ "entry.h", "libs_2karm-sys_2entry_8h.html", "libs_2karm-sys_2entry_8h" ],
    [ "fd.cpp", "libs_2karm-sys_2fd_8cpp.html", "libs_2karm-sys_2fd_8cpp" ],
    [ "file.cpp", "file_8cpp.html", "file_8cpp" ],
    [ "info.cpp", "info_8cpp.html", "info_8cpp" ],
    [ "launch.cpp", "launch_8cpp.html", "launch_8cpp" ],
    [ "lookup.cpp", "lookup_8cpp.html", "lookup_8cpp" ],
    [ "message.cpp", "message_8cpp.html", "message_8cpp" ],
    [ "mmap.cpp", "mmap_8cpp.html", "mmap_8cpp" ],
    [ "mod.cpp", "karm-sys_2mod_8cpp.html", "karm-sys_2mod_8cpp" ],
    [ "mutex.cpp", "mutex_8cpp.html", "mutex_8cpp" ],
    [ "pid.cpp", "pid_8cpp.html", "pid_8cpp" ],
    [ "pipe.cpp", "karm-sys_2pipe_8cpp.html", "karm-sys_2pipe_8cpp" ],
    [ "proc.cpp", "proc_8cpp.html", "proc_8cpp" ],
    [ "sandbox.cpp", "libs_2karm-sys_2sandbox_8cpp.html", "libs_2karm-sys_2sandbox_8cpp" ],
    [ "socket.cpp", "socket_8cpp.html", "socket_8cpp" ],
    [ "stat.cpp", "stat_8cpp.html", "stat_8cpp" ],
    [ "time.cpp", "karm-sys_2time_8cpp.html", "karm-sys_2time_8cpp" ],
    [ "types.cpp", "karm-sys_2types_8cpp.html", "karm-sys_2types_8cpp" ]
];