export module Karm.Icu:ucd;

import Karm.Core;

// This file is generated by meta/scripts/ucd_compiler.py
namespace Karm::Icu {

// Unicode Character Database
// https://unicode.org/reports/tr44/

export constexpr Str UCD_VERSION = "17.0.0";

export enum struct Age {
    V1_1,
    V10_0,
    V11_0,
    V12_0,
    V12_1,
    V13_0,
    V14_0,
    V15_0,
    V15_1,
    V16_0,
    V17_0,
    V2_0,
    V2_1,
    V3_0,
    V3_1,
    V3_2,
    V4_0,
    V4_1,
    V5_0,
    V5_1,
    V5_2,
    V6_0,
    V6_1,
    V6_2,
    V6_3,
    V7_0,
    V8_0,
    V9_0,
    UNASSIGNED,

    _LEN,
};

export enum struct BidiClass {
    ARABIC_LETTER,
    ARABIC_NUMBER,
    PARAGRAPH_SEPARATOR,
    BOUNDARY_NEUTRAL,
    COMMON_SEPARATOR,
    EUROPEAN_NUMBER,
    EUROPEAN_SEPARATOR,
    EUROPEAN_TERMINATOR,
    FIRST_STRONG_ISOLATE,
    LEFT_TO_RIGHT,
    LEFT_TO_RIGHT_EMBEDDING,
    LEFT_TO_RIGHT_ISOLATE,
    LEFT_TO_RIGHT_OVERRIDE,
    NONSPACING_MARK,
    OTHER_NEUTRAL,
    POP_DIRECTIONAL_FORMAT,
    POP_DIRECTIONAL_ISOLATE,
    RIGHT_TO_LEFT,
    RIGHT_TO_LEFT_EMBEDDING,
    RIGHT_TO_LEFT_ISOLATE,
    RIGHT_TO_LEFT_OVERRIDE,
    SEGMENT_SEPARATOR,
    WHITE_SPACE,

    _LEN,
};

export enum struct Block {
    BASIC_LATIN,
    ADLAM,
    AEGEAN_NUMBERS,
    AHOM,
    ALCHEMICAL_SYMBOLS,
    ALPHABETIC_PRESENTATION_FORMS,
    ANATOLIAN_HIEROGLYPHS,
    ANCIENT_GREEK_MUSICAL_NOTATION,
    ANCIENT_GREEK_NUMBERS,
    ANCIENT_SYMBOLS,
    ARABIC,
    ARABIC_EXTENDED_A,
    ARABIC_EXTENDED_B,
    ARABIC_EXTENDED_C,
    ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS,
    ARABIC_PRESENTATION_FORMS_A,
    ARABIC_PRESENTATION_FORMS_B,
    ARABIC_SUPPLEMENT,
    ARMENIAN,
    ARROWS,
    AVESTAN,
    BALINESE,
    BAMUM,
    BAMUM_SUPPLEMENT,
    BASSA_VAH,
    BATAK,
    BENGALI,
    BERIA_ERFE,
    BHAIKSUKI,
    BLOCK_ELEMENTS,
    BOPOMOFO,
    BOPOMOFO_EXTENDED,
    BOX_DRAWING,
    BRAHMI,
    BRAILLE_PATTERNS,
    BUGINESE,
    BUHID,
    BYZANTINE_MUSICAL_SYMBOLS,
    CJK_UNIFIED_IDEOGRAPHS,
    CJK_COMPATIBILITY,
    CJK_COMPATIBILITY_FORMS,
    CJK_COMPATIBILITY_IDEOGRAPHS,
    CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_E,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_G,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_H,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_I,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_J,
    CJK_RADICALS_SUPPLEMENT,
    CJK_STROKES,
    CJK_SYMBOLS_AND_PUNCTUATION,
    CARIAN,
    CAUCASIAN_ALBANIAN,
    CHAKMA,
    CHAM,
    CHEROKEE,
    CHEROKEE_SUPPLEMENT,
    CHESS_SYMBOLS,
    CHORASMIAN,
    HANGUL_COMPATIBILITY_JAMO,
    CONTROL_PICTURES,
    COPTIC,
    COPTIC_EPACT_NUMBERS,
    COUNTING_ROD_NUMERALS,
    CUNEIFORM,
    CUNEIFORM_NUMBERS_AND_PUNCTUATION,
    CURRENCY_SYMBOLS,
    CYPRIOT_SYLLABARY,
    CYPRO_MINOAN,
    CYRILLIC,
    CYRILLIC_EXTENDED_A,
    CYRILLIC_EXTENDED_B,
    CYRILLIC_EXTENDED_C,
    CYRILLIC_EXTENDED_D,
    CYRILLIC_SUPPLEMENT,
    DESERET,
    DEVANAGARI,
    DEVANAGARI_EXTENDED,
    DEVANAGARI_EXTENDED_A,
    COMBINING_DIACRITICAL_MARKS,
    COMBINING_DIACRITICAL_MARKS_EXTENDED,
    COMBINING_DIACRITICAL_MARKS_FOR_SYMBOLS,
    COMBINING_DIACRITICAL_MARKS_SUPPLEMENT,
    DINGBATS,
    DIVES_AKURU,
    DOGRA,
    DOMINO_TILES,
    DUPLOYAN,
    EARLY_DYNASTIC_CUNEIFORM,
    EGYPTIAN_HIEROGLYPH_FORMAT_CONTROLS,
    EGYPTIAN_HIEROGLYPHS,
    EGYPTIAN_HIEROGLYPHS_EXTENDED_A,
    ELBASAN,
    ELYMAIC,
    EMOTICONS,
    ENCLOSED_ALPHANUMERICS,
    ENCLOSED_ALPHANUMERIC_SUPPLEMENT,
    ENCLOSED_CJK_LETTERS_AND_MONTHS,
    ENCLOSED_IDEOGRAPHIC_SUPPLEMENT,
    ETHIOPIC,
    ETHIOPIC_EXTENDED,
    ETHIOPIC_EXTENDED_A,
    ETHIOPIC_EXTENDED_B,
    ETHIOPIC_SUPPLEMENT,
    GARAY,
    GEOMETRIC_SHAPES,
    GEOMETRIC_SHAPES_EXTENDED,
    GEORGIAN,
    GEORGIAN_EXTENDED,
    GEORGIAN_SUPPLEMENT,
    GLAGOLITIC,
    GLAGOLITIC_SUPPLEMENT,
    GOTHIC,
    GRANTHA,
    GREEK_AND_COPTIC,
    GREEK_EXTENDED,
    GUJARATI,
    GUNJALA_GONDI,
    GURMUKHI,
    GURUNG_KHEMA,
    HALFWIDTH_AND_FULLWIDTH_FORMS,
    COMBINING_HALF_MARKS,
    HANGUL_SYLLABLES,
    HANIFI_ROHINGYA,
    HANUNOO,
    HATRAN,
    HEBREW,
    HIGH_PRIVATE_USE_SURROGATES,
    HIGH_SURROGATES,
    HIRAGANA,
    IDEOGRAPHIC_DESCRIPTION_CHARACTERS,
    IPA_EXTENSIONS,
    IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION,
    IMPERIAL_ARAMAIC,
    COMMON_INDIC_NUMBER_FORMS,
    INDIC_SIYAQ_NUMBERS,
    INSCRIPTIONAL_PAHLAVI,
    INSCRIPTIONAL_PARTHIAN,
    HANGUL_JAMO,
    HANGUL_JAMO_EXTENDED_A,
    HANGUL_JAMO_EXTENDED_B,
    JAVANESE,
    KAITHI,
    KAKTOVIK_NUMERALS,
    KANA_EXTENDED_A,
    KANA_EXTENDED_B,
    KANA_SUPPLEMENT,
    KANBUN,
    KANGXI_RADICALS,
    KANNADA,
    KATAKANA,
    KATAKANA_PHONETIC_EXTENSIONS,
    KAWI,
    KAYAH_LI,
    KHAROSHTHI,
    KHITAN_SMALL_SCRIPT,
    KHMER,
    KHMER_SYMBOLS,
    KHOJKI,
    KHUDAWADI,
    KIRAT_RAI,
    LAO,
    LATIN_1_SUPPLEMENT,
    LATIN_EXTENDED_A,
    LATIN_EXTENDED_ADDITIONAL,
    LATIN_EXTENDED_B,
    LATIN_EXTENDED_C,
    LATIN_EXTENDED_D,
    LATIN_EXTENDED_E,
    LATIN_EXTENDED_F,
    LATIN_EXTENDED_G,
    LEPCHA,
    LETTERLIKE_SYMBOLS,
    LIMBU,
    LINEAR_A,
    LINEAR_B_IDEOGRAMS,
    LINEAR_B_SYLLABARY,
    LISU,
    LISU_SUPPLEMENT,
    LOW_SURROGATES,
    LYCIAN,
    LYDIAN,
    MAHAJANI,
    MAHJONG_TILES,
    MAKASAR,
    MALAYALAM,
    MANDAIC,
    MANICHAEAN,
    MARCHEN,
    MASARAM_GONDI,
    MATHEMATICAL_ALPHANUMERIC_SYMBOLS,
    MATHEMATICAL_OPERATORS,
    MAYAN_NUMERALS,
    MEDEFAIDRIN,
    MEETEI_MAYEK,
    MEETEI_MAYEK_EXTENSIONS,
    MENDE_KIKAKUI,
    MEROITIC_CURSIVE,
    MEROITIC_HIEROGLYPHS,
    MIAO,
    MISCELLANEOUS_SYMBOLS_AND_ARROWS,
    MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A,
    MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B,
    MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS,
    MISCELLANEOUS_SYMBOLS,
    MISCELLANEOUS_SYMBOLS_SUPPLEMENT,
    MISCELLANEOUS_TECHNICAL,
    MODI,
    SPACING_MODIFIER_LETTERS,
    MODIFIER_TONE_LETTERS,
    MONGOLIAN,
    MONGOLIAN_SUPPLEMENT,
    MRO,
    MULTANI,
    MUSICAL_SYMBOLS,
    MYANMAR,
    MYANMAR_EXTENDED_A,
    MYANMAR_EXTENDED_B,
    MYANMAR_EXTENDED_C,
    NO_BLOCK,
    NKO,
    NABATAEAN,
    NAG_MUNDARI,
    NANDINAGARI,
    NEW_TAI_LUE,
    NEWA,
    NUMBER_FORMS,
    NUSHU,
    NYIAKENG_PUACHUE_HMONG,
    OPTICAL_CHARACTER_RECOGNITION,
    OGHAM,
    OL_CHIKI,
    OL_ONAL,
    OLD_HUNGARIAN,
    OLD_ITALIC,
    OLD_NORTH_ARABIAN,
    OLD_PERMIC,
    OLD_PERSIAN,
    OLD_SOGDIAN,
    OLD_SOUTH_ARABIAN,
    OLD_TURKIC,
    OLD_UYGHUR,
    ORIYA,
    ORNAMENTAL_DINGBATS,
    OSAGE,
    OSMANYA,
    OTTOMAN_SIYAQ_NUMBERS,
    PRIVATE_USE_AREA,
    PAHAWH_HMONG,
    PALMYRENE,
    PAU_CIN_HAU,
    PHAGS_PA,
    PHAISTOS_DISC,
    PHOENICIAN,
    PHONETIC_EXTENSIONS,
    PHONETIC_EXTENSIONS_SUPPLEMENT,
    PLAYING_CARDS,
    PSALTER_PAHLAVI,
    GENERAL_PUNCTUATION,
    REJANG,
    RUMI_NUMERAL_SYMBOLS,
    RUNIC,
    SAMARITAN,
    SAURASHTRA,
    SHARADA,
    SHARADA_SUPPLEMENT,
    SHAVIAN,
    SHORTHAND_FORMAT_CONTROLS,
    SIDDHAM,
    SIDETIC,
    SINHALA,
    SINHALA_ARCHAIC_NUMBERS,
    SMALL_FORM_VARIANTS,
    SMALL_KANA_EXTENSION,
    SOGDIAN,
    SORA_SOMPENG,
    SOYOMBO,
    SPECIALS,
    SUNDANESE,
    SUNDANESE_SUPPLEMENT,
    SUNUWAR,
    SUPPLEMENTAL_ARROWS_A,
    SUPPLEMENTAL_ARROWS_B,
    SUPPLEMENTAL_ARROWS_C,
    SUPPLEMENTAL_MATHEMATICAL_OPERATORS,
    SUPPLEMENTARY_PRIVATE_USE_AREA_A,
    SUPPLEMENTARY_PRIVATE_USE_AREA_B,
    SUPPLEMENTAL_PUNCTUATION,
    SUPPLEMENTAL_SYMBOLS_AND_PICTOGRAPHS,
    SUPERSCRIPTS_AND_SUBSCRIPTS,
    SUTTON_SIGNWRITING,
    SYLOTI_NAGRI,
    SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A,
    SYMBOLS_FOR_LEGACY_COMPUTING,
    SYMBOLS_FOR_LEGACY_COMPUTING_SUPPLEMENT,
    SYRIAC,
    SYRIAC_SUPPLEMENT,
    TAGALOG,
    TAGBANWA,
    TAGS,
    TAI_LE,
    TAI_THAM,
    TAI_VIET,
    TAI_XUAN_JING_SYMBOLS,
    TAI_YO,
    TAKRI,
    TAMIL,
    TAMIL_SUPPLEMENT,
    TANGSA,
    TANGUT,
    TANGUT_COMPONENTS,
    TANGUT_COMPONENTS_SUPPLEMENT,
    TANGUT_SUPPLEMENT,
    TELUGU,
    THAANA,
    THAI,
    TIBETAN,
    TIFINAGH,
    TIRHUTA,
    TODHRI,
    TOLONG_SIKI,
    TOTO,
    TRANSPORT_AND_MAP_SYMBOLS,
    TULU_TIGALARI,
    UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS,
    UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED,
    UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED_A,
    UGARITIC,
    VARIATION_SELECTORS,
    VARIATION_SELECTORS_SUPPLEMENT,
    VAI,
    VEDIC_EXTENSIONS,
    VERTICAL_FORMS,
    VITHKUQI,
    WANCHO,
    WARANG_CITI,
    YEZIDI,
    YI_RADICALS,
    YI_SYLLABLES,
    YIJING_HEXAGRAM_SYMBOLS,
    ZANABAZAR_SQUARE,
    ZNAMENNY_MUSICAL_NOTATION,

    _LEN,
};

export enum struct BidiPairedBracketType {
    CLOSE,
    NONE,
    OPEN,

    _LEN,
};

export enum struct CanonicalCombiningClass {
    NOT_REORDERED = 0,
    OVERLAY = 1,
    CCC10 = 10,
    CCC103 = 103,
    CCC107 = 107,
    CCC11 = 11,
    CCC118 = 118,
    CCC12 = 12,
    CCC122 = 122,
    CCC129 = 129,
    CCC13 = 13,
    CCC130 = 130,
    CCC132 = 132,
    CCC133 = 133,
    CCC14 = 14,
    CCC15 = 15,
    CCC16 = 16,
    CCC17 = 17,
    CCC18 = 18,
    CCC19 = 19,
    CCC20 = 20,
    ATTACHED_BELOW_LEFT = 200,
    ATTACHED_BELOW = 202,
    CCC21 = 21,
    ATTACHED_ABOVE = 214,
    ATTACHED_ABOVE_RIGHT = 216,
    BELOW_LEFT = 218,
    CCC22 = 22,
    BELOW = 220,
    BELOW_RIGHT = 222,
    LEFT = 224,
    RIGHT = 226,
    ABOVE_LEFT = 228,
    CCC23 = 23,
    ABOVE = 230,
    ABOVE_RIGHT = 232,
    DOUBLE_BELOW = 233,
    DOUBLE_ABOVE = 234,
    CCC24 = 24,
    IOTA_SUBSCRIPT = 240,
    CCC25 = 25,
    CCC26 = 26,
    CCC27 = 27,
    CCC28 = 28,
    CCC29 = 29,
    CCC30 = 30,
    CCC31 = 31,
    CCC32 = 32,
    CCC33 = 33,
    CCC34 = 34,
    CCC35 = 35,
    CCC36 = 36,
    HAN_READING = 6,
    NUKTA = 7,
    KANA_VOICING = 8,
    CCC84 = 84,
    VIRAMA = 9,
    CCC91 = 91,

    _LEN,
};

export enum struct DecompositionType {
    CANONICAL,
    COMPAT,
    CIRCLE,
    FINAL,
    FONT,
    FRACTION,
    INITIAL,
    ISOLATED,
    MEDIAL,
    NARROW,
    NOBREAK,
    NONE,
    SMALL,
    SQUARE,
    SUB,
    SUPER,
    VERTICAL,
    WIDE,

    _LEN,
};

export enum struct EastAsianWidth {
    AMBIGUOUS,
    FULLWIDTH,
    HALFWIDTH,
    NEUTRAL,
    NARROW,
    WIDE,

    _LEN,
};

export enum struct GeneralCategory {
    OTHER,
    CONTROL,
    FORMAT,
    UNASSIGNED,
    PRIVATE_USE,
    SURROGATE,
    LETTER,
    CASED_LETTER,
    LOWERCASE_LETTER,
    MODIFIER_LETTER,
    OTHER_LETTER,
    TITLECASE_LETTER,
    UPPERCASE_LETTER,
    MARK,
    SPACING_MARK,
    ENCLOSING_MARK,
    NONSPACING_MARK,
    NUMBER,
    DECIMAL_NUMBER,
    LETTER_NUMBER,
    OTHER_NUMBER,
    PUNCTUATION,
    CONNECTOR_PUNCTUATION,
    DASH_PUNCTUATION,
    CLOSE_PUNCTUATION,
    FINAL_PUNCTUATION,
    INITIAL_PUNCTUATION,
    OTHER_PUNCTUATION,
    OPEN_PUNCTUATION,
    SYMBOL,
    CURRENCY_SYMBOL,
    MODIFIER_SYMBOL,
    MATH_SYMBOL,
    OTHER_SYMBOL,
    SEPARATOR,
    LINE_SEPARATOR,
    PARAGRAPH_SEPARATOR,
    SPACE_SEPARATOR,

    _LEN,
};

export enum struct GraphemeClusterBreak {
    CONTROL,
    CR,
    E_BASE,
    E_BASE_GAZ,
    E_MODIFIER,
    EXTEND,
    GLUE_AFTER_ZWJ,
    L,
    LF,
    LV,
    LVT,
    PREPEND,
    REGIONAL_INDICATOR,
    SPACINGMARK,
    T,
    V,
    OTHER,
    ZWJ,

    _LEN,
};

export enum struct HangulSyllableType {
    LEADING_JAMO,
    LV_SYLLABLE,
    LVT_SYLLABLE,
    NOT_APPLICABLE,
    TRAILING_JAMO,
    VOWEL_JAMO,

    _LEN,
};

export enum struct IdentifierStatus {
    ALLOWED,
    RESTRICTED,

    _LEN,
};

export enum struct IndicConjunctBreak {
    CONSONANT,
    EXTEND,
    LINKER,
    NONE,

    _LEN,
};

export enum struct IndicPositionalCategory {
    BOTTOM,
    BOTTOM_AND_LEFT,
    BOTTOM_AND_RIGHT,
    LEFT,
    LEFT_AND_RIGHT,
    NOT_APPLICABLE,
    OVERSTRUCK,
    RIGHT,
    TOP,
    TOP_AND_BOTTOM,
    TOP_AND_BOTTOM_AND_LEFT,
    TOP_AND_BOTTOM_AND_RIGHT,
    TOP_AND_LEFT,
    TOP_AND_LEFT_AND_RIGHT,
    TOP_AND_RIGHT,
    VISUAL_ORDER_LEFT,

    _LEN,
};

export enum struct IndicSyllabicCategory {
    AVAGRAHA,
    BINDU,
    BRAHMI_JOINING_NUMBER,
    CANTILLATION_MARK,
    CONSONANT,
    CONSONANT_DEAD,
    CONSONANT_FINAL,
    CONSONANT_HEAD_LETTER,
    CONSONANT_INITIAL_POSTFIXED,
    CONSONANT_KILLER,
    CONSONANT_MEDIAL,
    CONSONANT_PLACEHOLDER,
    CONSONANT_PRECEDING_REPHA,
    CONSONANT_PREFIXED,
    CONSONANT_SUBJOINED,
    CONSONANT_SUCCEEDING_REPHA,
    CONSONANT_WITH_STACKER,
    GEMINATION_MARK,
    INVISIBLE_STACKER,
    JOINER,
    MODIFYING_LETTER,
    NON_JOINER,
    NUKTA,
    NUMBER,
    NUMBER_JOINER,
    OTHER,
    PURE_KILLER,
    REGISTER_SHIFTER,
    REORDERING_KILLER,
    SYLLABLE_MODIFIER,
    TONE_LETTER,
    TONE_MARK,
    VIRAMA,
    VISARGA,
    VOWEL,
    VOWEL_DEPENDENT,
    VOWEL_INDEPENDENT,

    _LEN,
};

export enum struct JoiningGroup {
    AFRICAN_FEH,
    AFRICAN_NOON,
    AFRICAN_QAF,
    AIN,
    ALAPH,
    ALEF,
    BEH,
    BETH,
    BURUSHASKI_YEH_BARREE,
    DAL,
    DALATH_RISH,
    E,
    FARSI_YEH,
    FE,
    FEH,
    FINAL_SEMKATH,
    GAF,
    GAMAL,
    HAH,
    HANIFI_ROHINGYA_KINNA_YA,
    HANIFI_ROHINGYA_PA,
    HE,
    HEH,
    HEH_GOAL,
    HETH,
    KAF,
    KAPH,
    KASHMIRI_YEH,
    KHAPH,
    KNOTTED_HEH,
    LAM,
    LAMADH,
    MALAYALAM_BHA,
    MALAYALAM_JA,
    MALAYALAM_LLA,
    MALAYALAM_LLLA,
    MALAYALAM_NGA,
    MALAYALAM_NNA,
    MALAYALAM_NNNA,
    MALAYALAM_NYA,
    MALAYALAM_RA,
    MALAYALAM_SSA,
    MALAYALAM_TTA,
    MANICHAEAN_ALEPH,
    MANICHAEAN_AYIN,
    MANICHAEAN_BETH,
    MANICHAEAN_DALETH,
    MANICHAEAN_DHAMEDH,
    MANICHAEAN_FIVE,
    MANICHAEAN_GIMEL,
    MANICHAEAN_HETH,
    MANICHAEAN_HUNDRED,
    MANICHAEAN_KAPH,
    MANICHAEAN_LAMEDH,
    MANICHAEAN_MEM,
    MANICHAEAN_NUN,
    MANICHAEAN_ONE,
    MANICHAEAN_PE,
    MANICHAEAN_QOPH,
    MANICHAEAN_RESH,
    MANICHAEAN_SADHE,
    MANICHAEAN_SAMEKH,
    MANICHAEAN_TAW,
    MANICHAEAN_TEN,
    MANICHAEAN_TETH,
    MANICHAEAN_THAMEDH,
    MANICHAEAN_TWENTY,
    MANICHAEAN_WAW,
    MANICHAEAN_YODH,
    MANICHAEAN_ZAYIN,
    MEEM,
    MIM,
    NO_JOINING_GROUP,
    NOON,
    NUN,
    NYA,
    PE,
    QAF,
    QAPH,
    REH,
    REVERSED_PE,
    ROHINGYA_YEH,
    SAD,
    SADHE,
    SEEN,
    SEMKATH,
    SHIN,
    STRAIGHT_WAW,
    SWASH_KAF,
    SYRIAC_WAW,
    TAH,
    TAW,
    TEH_MARBUTA,
    TEH_MARBUTA_GOAL,
    TETH,
    THIN_NOON,
    THIN_YEH,
    VERTICAL_TAIL,
    WAW,
    YEH,
    YEH_BARREE,
    YEH_WITH_TAIL,
    YUDH,
    YUDH_HE,
    ZAIN,
    ZHAIN,

    _LEN,
};

export enum struct JoiningType {
    JOIN_CAUSING,
    DUAL_JOINING,
    LEFT_JOINING,
    RIGHT_JOINING,
    TRANSPARENT,
    NON_JOINING,

    _LEN,
};

export enum struct LineBreak {
    AMBIGUOUS,
    AKSARA,
    ALPHABETIC,
    AKSARA_PREBASE,
    AKSARA_START,
    BREAK_BOTH,
    BREAK_AFTER,
    BREAK_BEFORE,
    MANDATORY_BREAK,
    CONTINGENT_BREAK,
    CONDITIONAL_JAPANESE_STARTER,
    CLOSE_PUNCTUATION,
    COMBINING_MARK,
    CLOSE_PARENTHESIS,
    CARRIAGE_RETURN,
    E_BASE,
    E_MODIFIER,
    EXCLAMATION,
    GLUE,
    H2,
    H3,
    UNAMBIGUOUS_HYPHEN,
    HEBREW_LETTER,
    HYPHEN,
    IDEOGRAPHIC,
    INSEPARABLE,
    INFIX_NUMERIC,
    JL,
    JT,
    JV,
    LINE_FEED,
    NEXT_LINE,
    NONSTARTER,
    NUMERIC,
    OPEN_PUNCTUATION,
    POSTFIX_NUMERIC,
    PREFIX_NUMERIC,
    QUOTATION,
    REGIONAL_INDICATOR,
    COMPLEX_CONTEXT,
    SURROGATE,
    SPACE,
    BREAK_SYMBOLS,
    VIRAMA_FINAL,
    VIRAMA,
    WORD_JOINER,
    UNKNOWN,
    ZWSPACE,
    ZWJ,

    _LEN,
};

export enum struct QuickCheck {
    MAYBE,
    NO,
    YES,

    _LEN,
};

export enum struct NumericType {
    DECIMAL,
    DIGIT,
    NONE,
    NUMERIC,

    _LEN,
};

export enum struct SentenceBreak {
    ATERM,
    CLOSE,
    CR,
    EXTEND,
    FORMAT,
    OLETTER,
    LF,
    LOWER,
    NUMERIC,
    SCONTINUE,
    SEP,
    SP,
    STERM,
    UPPER,
    OTHER,

    _LEN,
};

export enum struct Script {
    ADLAM,
    AFAK,
    CAUCASIAN_ALBANIAN,
    AHOM,
    ARABIC,
    ARAN,
    IMPERIAL_ARAMAIC,
    ARMENIAN,
    AVESTAN,
    BALINESE,
    BAMUM,
    BASSA_VAH,
    BATAK,
    BENGALI,
    BERIA_ERFE,
    BHAIKSUKI,
    BLIS,
    BOPOMOFO,
    BRAHMI,
    BRAILLE,
    BUGINESE,
    BUHID,
    CHAKMA,
    CANADIAN_ABORIGINAL,
    CARIAN,
    CHAM,
    CHEROKEE,
    CHORASMIAN,
    CIRT,
    COPTIC,
    CYPRO_MINOAN,
    CYPRIOT,
    CYRILLIC,
    CYRS,
    DEVANAGARI,
    DIVES_AKURU,
    DOGRA,
    DESERET,
    DUPLOYAN,
    EGYD,
    EGYH,
    EGYPTIAN_HIEROGLYPHS,
    ELBASAN,
    ELYMAIC,
    ETHIOPIC,
    GARAY,
    GEOK,
    GEORGIAN,
    GLAGOLITIC,
    GUNJALA_GONDI,
    MASARAM_GONDI,
    GOTHIC,
    GRANTHA,
    GREEK,
    GUJARATI,
    GURUNG_KHEMA,
    GURMUKHI,
    HANB,
    HANGUL,
    HAN,
    HANUNOO,
    HANS,
    HANT,
    HATRAN,
    HEBREW,
    HIRAGANA,
    ANATOLIAN_HIEROGLYPHS,
    PAHAWH_HMONG,
    NYIAKENG_PUACHUE_HMONG,
    HNTL,
    KATAKANA_OR_HIRAGANA,
    OLD_HUNGARIAN,
    INDS,
    OLD_ITALIC,
    JAMO,
    JAVANESE,
    JPAN,
    JURC,
    KAYAH_LI,
    KATAKANA,
    KAWI,
    KHAROSHTHI,
    KHMER,
    KHOJKI,
    KHITAN_SMALL_SCRIPT,
    KANNADA,
    KORE,
    KPEL,
    KIRAT_RAI,
    KAITHI,
    TAI_THAM,
    LAO,
    LATF,
    LATG,
    LATIN,
    LEPCHA,
    LIMBU,
    LINEAR_A,
    LINEAR_B,
    LISU,
    LOMA,
    LYCIAN,
    LYDIAN,
    MAHAJANI,
    MAKASAR,
    MANDAIC,
    MANICHAEAN,
    MARCHEN,
    MAYA,
    MEDEFAIDRIN,
    MENDE_KIKAKUI,
    MEROITIC_CURSIVE,
    MEROITIC_HIEROGLYPHS,
    MALAYALAM,
    MODI,
    MONGOLIAN,
    MOON,
    MRO,
    MEETEI_MAYEK,
    MULTANI,
    MYANMAR,
    NAG_MUNDARI,
    NANDINAGARI,
    OLD_NORTH_ARABIAN,
    NABATAEAN,
    NEWA,
    NKGB,
    NKO,
    NUSHU,
    OGHAM,
    OL_CHIKI,
    OL_ONAL,
    OLD_TURKIC,
    ORIYA,
    OSAGE,
    OSMANYA,
    OLD_UYGHUR,
    PALMYRENE,
    PAU_CIN_HAU,
    OLD_PERMIC,
    PHAGS_PA,
    INSCRIPTIONAL_PAHLAVI,
    PSALTER_PAHLAVI,
    PHLV,
    PHOENICIAN,
    MIAO,
    INSCRIPTIONAL_PARTHIAN,
    REJANG,
    HANIFI_ROHINGYA,
    RORO,
    RUNIC,
    SAMARITAN,
    SARA,
    OLD_SOUTH_ARABIAN,
    SAURASHTRA,
    SIGNWRITING,
    SHAVIAN,
    SHARADA,
    SIDDHAM,
    SIDETIC,
    KHUDAWADI,
    SINHALA,
    SOGDIAN,
    OLD_SOGDIAN,
    SORA_SOMPENG,
    SOYOMBO,
    SUNDANESE,
    SUNUWAR,
    SYLOTI_NAGRI,
    SYRIAC,
    SYRE,
    SYRJ,
    SYRN,
    TAGBANWA,
    TAKRI,
    TAI_LE,
    NEW_TAI_LUE,
    TAMIL,
    TANGUT,
    TAI_VIET,
    TAI_YO,
    TELUGU,
    TENG,
    TIFINAGH,
    TAGALOG,
    THAANA,
    THAI,
    TIBETAN,
    TIRHUTA,
    TANGSA,
    TODHRI,
    TOLONG_SIKI,
    TOTO,
    TULU_TIGALARI,
    UGARITIC,
    VAI,
    VISP,
    VITHKUQI,
    WARANG_CITI,
    WANCHO,
    WOLE,
    OLD_PERSIAN,
    CUNEIFORM,
    YEZIDI,
    YI,
    ZANABAZAR_SQUARE,
    INHERITED,
    ZMTH,
    ZSYE,
    ZSYM,
    ZXXX,
    COMMON,
    UNKNOWN,

    _LEN,
};

export enum struct VerticalOrientation {
    ROTATED,
    TRANSFORMED_ROTATED,
    TRANSFORMED_UPRIGHT,
    UPRIGHT,

    _LEN,
};

export enum struct WordBreak {
    CR,
    DOUBLE_QUOTE,
    E_BASE,
    E_BASE_GAZ,
    E_MODIFIER,
    EXTENDNUMLET,
    EXTEND,
    FORMAT,
    GLUE_AFTER_ZWJ,
    HEBREW_LETTER,
    KATAKANA,
    ALETTER,
    LF,
    MIDNUMLET,
    MIDLETTER,
    MIDNUM,
    NEWLINE,
    NUMERIC,
    REGIONAL_INDICATOR,
    SINGLE_QUOTE,
    WSEGSPACE,
    OTHER,
    ZWJ,

    _LEN,
};

#include "defs/tables/age.inc"
#include "defs/tables/ascii-hex-digit.inc"
#include "defs/tables/alnum.inc"
#include "defs/tables/alphabetic.inc"
#include "defs/tables/basic-emoji.inc"
#include "defs/tables/bidi-class.inc"
#include "defs/tables/bidi-control.inc"
#include "defs/tables/bidi-mirrored.inc"
#include "defs/tables/blank.inc"
#include "defs/tables/block.inc"
#include "defs/tables/bidi-mirroring-glyph.inc"
#include "defs/tables/bidi-paired-bracket-type.inc"
#include "defs/tables/cased.inc"
#include "defs/tables/canonical-combining-class.inc"
#include "defs/tables/case-ignorable.inc"
#include "defs/tables/full-composition-exclusion.inc"
#include "defs/tables/changes-when-casefolded.inc"
#include "defs/tables/changes-when-casemapped.inc"
#include "defs/tables/changes-when-nfkc-casefolded.inc"
#include "defs/tables/changes-when-lowercased.inc"
#include "defs/tables/changes-when-titlecased.inc"
#include "defs/tables/changes-when-uppercased.inc"
#include "defs/tables/dash.inc"
#include "defs/tables/deprecated.inc"
#include "defs/tables/default-ignorable-code-point.inc"
#include "defs/tables/diacritic.inc"
#include "defs/tables/decomposition-type.inc"
#include "defs/tables/east-asian-width.inc"
#include "defs/tables/emoji-modifier-base.inc"
#include "defs/tables/emoji-component.inc"
#include "defs/tables/emoji-modifier.inc"
#include "defs/tables/emoji.inc"
#include "defs/tables/emoji-keycap-sequence.inc"
#include "defs/tables/emoji-presentation.inc"
#include "defs/tables/extender.inc"
#include "defs/tables/extended-pictographic.inc"
#include "defs/tables/general-category.inc"
#include "defs/tables/grapheme-cluster-break.inc"
#include "defs/tables/graph.inc"
#include "defs/tables/grapheme-base.inc"
#include "defs/tables/grapheme-extend.inc"
#include "defs/tables/grapheme-link.inc"
#include "defs/tables/hex-digit.inc"
#include "defs/tables/hangul-syllable-type.inc"
#include "defs/tables/hyphen.inc"
#include "defs/tables/id-continue.inc"
#include "defs/tables/id-compat-math-continue.inc"
#include "defs/tables/id-compat-math-start.inc"
#include "defs/tables/ideographic.inc"
#include "defs/tables/id-start.inc"
#include "defs/tables/ids-binary-operator.inc"
#include "defs/tables/ids-trinary-operator.inc"
#include "defs/tables/identifier-status.inc"
#include "defs/tables/ids-unary-operator.inc"
#include "defs/tables/indic-conjunct-break.inc"
#include "defs/tables/indic-positional-category.inc"
#include "defs/tables/indic-syllabic-category.inc"
#include "defs/tables/joining-group.inc"
#include "defs/tables/join-control.inc"
#include "defs/tables/joining-type.inc"
#include "defs/tables/keh-no-mirror.inc"
#include "defs/tables/keh-no-rotate.inc"
#include "defs/tables/line-break.inc"
#include "defs/tables/lead-canonical-combining-class.inc"
#include "defs/tables/logical-order-exception.inc"
#include "defs/tables/lowercase.inc"
#include "defs/tables/math.inc"
#include "defs/tables/modifier-combining-mark.inc"
#include "defs/tables/noncharacter-code-point.inc"
#include "defs/tables/nfc-inert.inc"
#include "defs/tables/nfc-quick-check.inc"
#include "defs/tables/nfd-inert.inc"
#include "defs/tables/nfd-quick-check.inc"
#include "defs/tables/nfkc-inert.inc"
#include "defs/tables/nfkc-quick-check.inc"
#include "defs/tables/nfkd-inert.inc"
#include "defs/tables/nfkd-quick-check.inc"
#include "defs/tables/numeric-type.inc"
#include "defs/tables/pattern-syntax.inc"
#include "defs/tables/pattern-white-space.inc"
#include "defs/tables/prepended-concatenation-mark.inc"
#include "defs/tables/print.inc"
#include "defs/tables/quotation-mark.inc"
#include "defs/tables/radical.inc"
#include "defs/tables/rgi-emoji.inc"
#include "defs/tables/rgi-emoji-flag-sequence.inc"
#include "defs/tables/rgi-emoji-modifier-sequence.inc"
#include "defs/tables/rgi-emoji-tag-sequence.inc"
#include "defs/tables/rgi-emoji-zwj-sequence.inc"
#include "defs/tables/regional-indicator.inc"
#include "defs/tables/sentence-break.inc"
#include "defs/tables/script.inc"
#include "defs/tables/soft-dotted.inc"
#include "defs/tables/segment-starter.inc"
#include "defs/tables/case-sensitive.inc"
#include "defs/tables/sentence-terminal.inc"
#include "defs/tables/trail-canonical-combining-class.inc"
#include "defs/tables/terminal-punctuation.inc"
#include "defs/tables/unified-ideograph.inc"
#include "defs/tables/uppercase.inc"
#include "defs/tables/vertical-orientation.inc"
#include "defs/tables/variation-selector.inc"
#include "defs/tables/word-break.inc"
#include "defs/tables/white-space.inc"
#include "defs/tables/xdigit.inc"
#include "defs/tables/xid-continue.inc"
#include "defs/tables/xid-start.inc"
export struct Properties {
    Rune _rune;

    static Properties of(Rune r) { return Properties(r); }

    Age age() const {
        return static_cast<Age>(_AgePages[(_AgeIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    bool asciiHexDigit() const {
        return (_AsciiHexDigitPages[(_AsciiHexDigitIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool alnum() const {
        return (_AlnumPages[(_AlnumIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool alphabetic() const {
        return (_AlphabeticPages[(_AlphabeticIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool basicEmoji() const {
        return (_BasicEmojiPages[(_BasicEmojiIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    BidiClass bidiClass() const {
        return static_cast<BidiClass>(_BidiClassPages[(_BidiClassIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    bool bidiControl() const {
        return (_BidiControlPages[(_BidiControlIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool bidiMirrored() const {
        return (_BidiMirroredPages[(_BidiMirroredIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool blank() const {
        return (_BlankPages[(_BlankIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    Block block() const {
        return static_cast<Block>(_BlockPages[(_BlockIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    Rune bidiMirroringGlyph() const {
        return static_cast<Rune>(_BidiMirroringGlyphPages[(_BidiMirroringGlyphIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    // TODO: Ignored property BidiPairedBracket

    BidiPairedBracketType bidiPairedBracketType() const {
        return static_cast<BidiPairedBracketType>(_BidiPairedBracketTypePages[(_BidiPairedBracketTypeIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    bool cased() const {
        return (_CasedPages[(_CasedIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    CanonicalCombiningClass canonicalCombiningClass() const {
        return static_cast<CanonicalCombiningClass>(_CanonicalCombiningClassPages[(_CanonicalCombiningClassIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    // TODO: Ignored property CaseFolding

    bool caseIgnorable() const {
        return (_CaseIgnorablePages[(_CaseIgnorableIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    // TODO: Ignored property KMandarin

    // TODO: Ignored property KTotalStrokes

    // TODO: Ignored property KUnihanCore2020

    bool fullCompositionExclusion() const {
        return (_FullCompositionExclusionPages[(_FullCompositionExclusionIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    // TODO: Ignored property ConditionalCaseMappings

    bool changesWhenCasefolded() const {
        return (_ChangesWhenCasefoldedPages[(_ChangesWhenCasefoldedIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool changesWhenCasemapped() const {
        return (_ChangesWhenCasemappedPages[(_ChangesWhenCasemappedIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool changesWhenNfkcCasefolded() const {
        return (_ChangesWhenNfkcCasefoldedPages[(_ChangesWhenNfkcCasefoldedIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool changesWhenLowercased() const {
        return (_ChangesWhenLowercasedPages[(_ChangesWhenLowercasedIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool changesWhenTitlecased() const {
        return (_ChangesWhenTitlecasedPages[(_ChangesWhenTitlecasedIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool changesWhenUppercased() const {
        return (_ChangesWhenUppercasedPages[(_ChangesWhenUppercasedIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool dash() const {
        return (_DashPages[(_DashIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool deprecated() const {
        return (_DeprecatedPages[(_DeprecatedIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool defaultIgnorableCodePoint() const {
        return (_DefaultIgnorableCodePointPages[(_DefaultIgnorableCodePointIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool diacritic() const {
        return (_DiacriticPages[(_DiacriticIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    // TODO: Ignored property DecompositionMapping

    DecompositionType decompositionType() const {
        return static_cast<DecompositionType>(_DecompositionTypePages[(_DecompositionTypeIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    EastAsianWidth eastAsianWidth() const {
        return static_cast<EastAsianWidth>(_EastAsianWidthPages[(_EastAsianWidthIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    bool emojiModifierBase() const {
        return (_EmojiModifierBasePages[(_EmojiModifierBaseIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool emojiComponent() const {
        return (_EmojiComponentPages[(_EmojiComponentIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool emojiModifier() const {
        return (_EmojiModifierPages[(_EmojiModifierIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool emoji() const {
        return (_EmojiPages[(_EmojiIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool emojiKeycapSequence() const {
        return (_EmojiKeycapSequencePages[(_EmojiKeycapSequenceIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool emojiPresentation() const {
        return (_EmojiPresentationPages[(_EmojiPresentationIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    // TODO: Ignored property EquivalentUnifiedIdeograph

    bool extender() const {
        return (_ExtenderPages[(_ExtenderIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool extendedPictographic() const {
        return (_ExtendedPictographicPages[(_ExtendedPictographicIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    // TODO: Ignored property FcNfkcClosure

    GeneralCategory generalCategory() const {
        return static_cast<GeneralCategory>(_GeneralCategoryPages[(_GeneralCategoryIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    GraphemeClusterBreak graphemeClusterBreak() const {
        return static_cast<GraphemeClusterBreak>(_GraphemeClusterBreakPages[(_GraphemeClusterBreakIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    // TODO: Ignored property GeneralCategoryMask

    bool graph() const {
        return (_GraphPages[(_GraphIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool graphemeBase() const {
        return (_GraphemeBasePages[(_GraphemeBaseIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool graphemeExtend() const {
        return (_GraphemeExtendPages[(_GraphemeExtendIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool graphemeLink() const {
        return (_GraphemeLinkPages[(_GraphemeLinkIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool hexDigit() const {
        return (_HexDigitPages[(_HexDigitIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    HangulSyllableType hangulSyllableType() const {
        return static_cast<HangulSyllableType>(_HangulSyllableTypePages[(_HangulSyllableTypeIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    bool hyphen() const {
        return (_HyphenPages[(_HyphenIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool idContinue() const {
        return (_IdContinuePages[(_IdContinueIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool idCompatMathContinue() const {
        return (_IdCompatMathContinuePages[(_IdCompatMathContinueIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool idCompatMathStart() const {
        return (_IdCompatMathStartPages[(_IdCompatMathStartIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool ideographic() const {
        return (_IdeographicPages[(_IdeographicIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool idStart() const {
        return (_IdStartPages[(_IdStartIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool idsBinaryOperator() const {
        return (_IdsBinaryOperatorPages[(_IdsBinaryOperatorIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool idsTrinaryOperator() const {
        return (_IdsTrinaryOperatorPages[(_IdsTrinaryOperatorIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    IdentifierStatus identifierStatus() const {
        return static_cast<IdentifierStatus>(_IdentifierStatusPages[(_IdentifierStatusIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    bool idsUnaryOperator() const {
        return (_IdsUnaryOperatorPages[(_IdsUnaryOperatorIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    // TODO: Ignored property IdentifierType

    IndicConjunctBreak indicConjunctBreak() const {
        return static_cast<IndicConjunctBreak>(_IndicConjunctBreakPages[(_IndicConjunctBreakIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    IndicPositionalCategory indicPositionalCategory() const {
        return static_cast<IndicPositionalCategory>(_IndicPositionalCategoryPages[(_IndicPositionalCategoryIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    IndicSyllabicCategory indicSyllabicCategory() const {
        return static_cast<IndicSyllabicCategory>(_IndicSyllabicCategoryPages[(_IndicSyllabicCategoryIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    // TODO: Ignored property IsoComment

    JoiningGroup joiningGroup() const {
        return static_cast<JoiningGroup>(_JoiningGroupPages[(_JoiningGroupIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    bool joinControl() const {
        return (_JoinControlPages[(_JoinControlIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    JoiningType joiningType() const {
        return static_cast<JoiningType>(_JoiningTypePages[(_JoiningTypeIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    // TODO: Ignored property KEhCat

    // TODO: Ignored property KEhDesc

    // TODO: Ignored property KEhHg

    // TODO: Ignored property KEhIfao

    // TODO: Ignored property KEhJsesh

    bool kehNoMirror() const {
        return (_KEhNoMirrorPages[(_KEhNoMirrorIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool kehNoRotate() const {
        return (_KEhNoRotatePages[(_KEhNoRotateIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    LineBreak lineBreak() const {
        return static_cast<LineBreak>(_LineBreakPages[(_LineBreakIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    // TODO: Ignored property LowercaseMapping

    CanonicalCombiningClass leadCanonicalCombiningClass() const {
        return static_cast<CanonicalCombiningClass>(_LeadCanonicalCombiningClassPages[(_LeadCanonicalCombiningClassIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    bool logicalOrderException() const {
        return (_LogicalOrderExceptionPages[(_LogicalOrderExceptionIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool lowercase() const {
        return (_LowercasePages[(_LowercaseIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool math() const {
        return (_MathPages[(_MathIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool modifierCombiningMark() const {
        return (_ModifierCombiningMarkPages[(_ModifierCombiningMarkIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    // TODO: Ignored property Name

    // TODO: Ignored property Unicode1Name

    // TODO: Ignored property NameAlias

    bool noncharacterCodePoint() const {
        return (_NoncharacterCodePointPages[(_NoncharacterCodePointIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool nfcInert() const {
        return (_NfcInertPages[(_NfcInertIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    QuickCheck nfcQuickCheck() const {
        return static_cast<QuickCheck>(_NfcQuickCheckPages[(_NfcQuickCheckIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    bool nfdInert() const {
        return (_NfdInertPages[(_NfdInertIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    QuickCheck nfdQuickCheck() const {
        return static_cast<QuickCheck>(_NfdQuickCheckPages[(_NfdQuickCheckIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    // TODO: Ignored property NfkcCasefold

    bool nfkcInert() const {
        return (_NfkcInertPages[(_NfkcInertIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    QuickCheck nfkcQuickCheck() const {
        return static_cast<QuickCheck>(_NfkcQuickCheckPages[(_NfkcQuickCheckIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    // TODO: Ignored property NfkcSimpleCasefold

    bool nfkdInert() const {
        return (_NfkdInertPages[(_NfkdInertIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    QuickCheck nfkdQuickCheck() const {
        return static_cast<QuickCheck>(_NfkdQuickCheckPages[(_NfkdQuickCheckIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    NumericType numericType() const {
        return static_cast<NumericType>(_NumericTypePages[(_NumericTypeIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    // TODO: Ignored property NumericValue

    bool patternSyntax() const {
        return (_PatternSyntaxPages[(_PatternSyntaxIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool patternWhiteSpace() const {
        return (_PatternWhiteSpacePages[(_PatternWhiteSpaceIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool prependedConcatenationMark() const {
        return (_PrependedConcatenationMarkPages[(_PrependedConcatenationMarkIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool print() const {
        return (_PrintPages[(_PrintIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool quotationMark() const {
        return (_QuotationMarkPages[(_QuotationMarkIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool radical() const {
        return (_RadicalPages[(_RadicalIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool rgiEmoji() const {
        return (_RgiEmojiPages[(_RgiEmojiIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool rgiEmojiFlagSequence() const {
        return (_RgiEmojiFlagSequencePages[(_RgiEmojiFlagSequenceIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool rgiEmojiModifierSequence() const {
        return (_RgiEmojiModifierSequencePages[(_RgiEmojiModifierSequenceIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool rgiEmojiTagSequence() const {
        return (_RgiEmojiTagSequencePages[(_RgiEmojiTagSequenceIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool rgiEmojiZwjSequence() const {
        return (_RgiEmojiZwjSequencePages[(_RgiEmojiZwjSequenceIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool regionalIndicator() const {
        return (_RegionalIndicatorPages[(_RegionalIndicatorIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    SentenceBreak sentenceBreak() const {
        return static_cast<SentenceBreak>(_SentenceBreakPages[(_SentenceBreakIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    Script script() const {
        return static_cast<Script>(_ScriptPages[(_ScriptIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    // TODO: Ignored property SimpleCaseFolding

    // TODO: Ignored property ScriptExtensions

    bool softDotted() const {
        return (_SoftDottedPages[(_SoftDottedIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool segmentStarter() const {
        return (_SegmentStarterPages[(_SegmentStarterIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool caseSensitive() const {
        return (_CaseSensitivePages[(_CaseSensitiveIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    // TODO: Ignored property SimpleLowercaseMapping

    // TODO: Ignored property SimpleTitlecaseMapping

    bool sentenceTerminal() const {
        return (_SentenceTerminalPages[(_SentenceTerminalIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    // TODO: Ignored property SimpleUppercaseMapping

    // TODO: Ignored property TitlecaseMapping

    CanonicalCombiningClass trailCanonicalCombiningClass() const {
        return static_cast<CanonicalCombiningClass>(_TrailCanonicalCombiningClassPages[(_TrailCanonicalCombiningClassIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    bool terminalPunctuation() const {
        return (_TerminalPunctuationPages[(_TerminalPunctuationIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    // TODO: Ignored property TurkicCaseFolding

    // TODO: Ignored property UppercaseMapping

    bool unifiedIdeograph() const {
        return (_UnifiedIdeographPages[(_UnifiedIdeographIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool uppercase() const {
        return (_UppercasePages[(_UppercaseIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    VerticalOrientation verticalOrientation() const {
        return static_cast<VerticalOrientation>(_VerticalOrientationPages[(_VerticalOrientationIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    bool variationSelector() const {
        return (_VariationSelectorPages[(_VariationSelectorIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    WordBreak wordBreak() const {
        return static_cast<WordBreak>(_WordBreakPages[(_WordBreakIndirect[_rune >> 8] << 8) + (_rune & 255)]);
    }

    bool whiteSpace() const {
        return (_WhiteSpacePages[(_WhiteSpaceIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool xdigit() const {
        return (_XdigitPages[(_XdigitIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool xidContinue() const {
        return (_XidContinuePages[(_XidContinueIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool xidStart() const {
        return (_XidStartPages[(_XidStartIndirect[_rune >> 8] << 4) + ((_rune & 255) >> 4)] >> (_rune & 15)) & 1;
    }

    bool bmp() const { return _rune >= 0x0000 and _rune <= 0xffff; }

    bool supplementary() const { return _rune >= 0x10000 and _rune <= 0x10ffff; }

};

} // namespace Karm::Icu
