export module Karm.Ir.Spirv:grammar;

import Karm.Core;

// This file is generated by meta/scripts/spirv_compiler.py
namespace Karm::Ir::Spirv {
export constexpr u32 MAGIC_NUMBER = 0x07230203;
export constexpr u32 MAJOR_VERSION = 1;
export constexpr u32 MINOR_VERSION = 6;
export constexpr u32 REVISION = 7;
} // namespace Karm::Ir::Spirv
