import dataclasses as dc
import change_case

@dc.dataclass
class Emoji:
    group : str = ""
    subgroup : str = ""


with open("src/karm-icu/res/emoji-test.txt", "r") as f:
    groups = list()
    subgroups = list()

    group = ""
    subgroup = ""
    for line in f:
        line = line.strip()
        try:
            if line.startswith("# group: "):
                group = line.split(":", 1)[1].strip()
                if group not in groups: 
                    groups.append(group)
            elif line.startswith("# subgroup: "):
                subgroup = line.split(":", 1)[1].strip()
                if subgroup not in subgroups: 
                    subgroups.append(subgroup)
            elif line.startswith("#"):
                pass
            elif line == "":
                pass
            elif ";" in line and "#" in line:
                prefix, comment = line.split("#", 1)
                components, qualified = [s.strip() for s in prefix.split(";", 1)]
                pass
            else:
                print("unknown line type: " + line)
        except Exception as e:
            print("Failed to process: " + line)
            raise e

    print("export module Karm.Icu:emoji;\n")
    print("import Karm.Core;\n")
    print("// This file is generated by meta/scripts/emoji_compiler.py")
    print("namespace Karm::Icu {\n")
    print("export enum struct EmojiGroup {")
    for g in groups:
        print(f"    {change_case.to_constant_case(g.replace("&", "and"))},")
    print("    _LEN,")
    print("};\n")

    print("export enum struct EmojiSubGroup {")
    for g in subgroups:
        print(f"    {change_case.to_constant_case(g.replace("&", "and"))},")
    print("    _LEN,")
    print("};\n")
    print("} // namespace Karm::Icu")

