import json
import change_case


def loadGramar():
    with open("src/karm-ir/spirv/res/spirv.core.grammar.json", "r") as f:
        return json.load(f)


grammar = loadGramar()

# strip instruction without a version or "None" version
grammar["instructions"] = [
    op for op in grammar["instructions"] if op.get("version") != "None"
]

with open("src/karm-ir/spirv/defs/instructions.inc", "w") as out:
    for op in grammar["instructions"]:
        name = change_case.to_constant_case(op["opname"])
        print(f"INSTRUCTION({name[3:]}, {op['opcode']}, {op['opname']})", file=out)

with open("src/karm-ir/spirv/grammar.cpp", "w") as out:
    print("export module Karm.Ir.Spirv:grammar;\n", file=out)
    print("import Karm.Core;\n", file=out)
    print("// This file is generated by meta/scripts/spirv_compiler.py", file=out)
    print("namespace Karm::Ir::Spirv {", file=out)

    print(f"export constexpr u32 MAGIC_NUMBER = {grammar['magic_number']};", file=out)
    print(f"export constexpr u32 MAJOR_VERSION = {grammar['major_version']};", file=out)
    print(f"export constexpr u32 MINOR_VERSION = {grammar['minor_version']};", file=out)
    print(f"export constexpr u32 REVISION = {grammar['revision']};", file=out)

    print("} // namespace Karm::Ir::Spirv", file=out)

import subprocess

subprocess.run(["clang-format", "-i", "src/karm-ir/spirv/grammar.cpp"])
